MasterCard.Web/Models/ErrorViewModel.cs
namespace MasterCard.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MasterCard.Web/Areas/Admin/AdminViewComponents/AdminDashboardViewComponent.cs
using MasterCard.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System;

namespace MasterCard.Web.Areas.Admin.AdminViewComponents
{
    public class AdminDashboardViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View(new CardViewModel());
        }

        [HttpPost]
        public IViewComponentResult ProcessForm(CardViewModel model)
        {
            if (ModelState.IsValid)
            {
                // Process the data (e.g., save to database)
                // ...

                // Optionally redirect or return a different view
                Console.Write(ModelState.ToString());
            }

            // If model is invalid, return the original view with the model to show errors
            return View(model);
        }
    }
}

MasterCard.Web/Areas/Admin/Controllers/CategoryController.cs
using MasterCard.Service;
using Microsoft.AspNetCore.Mvc;

namespace MasterCard.Web.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        private readonly CategoryService _categoryRepository;
        public CategoryController(CategoryService categoryRepository)
        {
            _categoryRepository=categoryRepository;
        }
        public IActionResult Index()
        {
            return View(_categoryRepository.Get());
        }
    }
}

MasterCard.Web/Areas/Admin/Controllers/HomeController.cs
using MasterCard.Domain.Cards;
using MasterCard.Service;
using MasterCard.Web.Models;
using MasterCard.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace MasterCard.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        private readonly CardService CardRepository;
        public HomeController(CardService cardRepository)
        {
            this.CardRepository = cardRepository;
        }
        public IActionResult Index()
        {
            var model = CardRepository.Get();
            return View("Index", model);
        }
        [HttpPost]
        public IActionResult Index(CardViewModel viewModel)
        {
            var card = new Card
            {
                Title = viewModel.Title,
                Description = viewModel.Description,
                Link = viewModel.Link,
                Icon = viewModel.Icon,
                IsDeleted = viewModel.IsDeleted,
                CardCategoryId = 1
            };
            CardRepository.Create(card);
            CardRepository.Save();

            return View();
        }
    }
}

MasterCard.Web/Controllers/HomeController.cs
using MasterCard.Data.Context;
using MasterCard.Service;
using MasterCard.Web.Models;
using MasterCard.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Linq;

namespace MasterCard.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly CardService _cardRepository;
        private readonly MasterCardContext _masterCardContext;

        public HomeController(CardService cardRepository, MasterCardContext masterCardContext)
        {
            _cardRepository = cardRepository;
            _masterCardContext = masterCardContext;
        }

        public IActionResult Index()
        {
            var model = _cardRepository.Get().Select(s => new CardViewModel
            {
                Id = s.Id,
                Title = s.Title,
                Description = s.Description,
                Icon = s.Icon,
                Link = s.Link
            });
            return View("Index", model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MasterCard.Web/ViewComponents/CategoriesViewComponent.cs
using MasterCard.Service;
using MasterCard.Web.ViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace MasterCard.Web.ViewComponents


{
    public class CategoriesViewComponent : ViewComponent
    {
        private readonly CategoryService CategoryRepository;
        public CategoriesViewComponent(CategoryService categoryRepository)
        {
            this.CategoryRepository = categoryRepository;
        }
        public IViewComponentResult Invoke()
        {
            var model = CategoryRepository.Get().Select(s => new CategoryViewModel
            {
                Id = s.Id,
                Title = s.Title,
         
            });
            return View("_CategoryList", model);
        }
    }
}

MasterCard.Web/Areas/Admin/Views/Home/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

MasterCard.Web/Areas/Admin/Views/Home/Index.cshtml
@model IEnumerable<MasterCard.Domain.Cards.Card>


<div>
    <div>
        <button class="btn btn-success" data-toggle="modal" data-target="#myModal">ایجاد لینک +</button>
    </div>

    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog">

            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">ایجاد پست لینک جدید</h4>
                </div>

                @await Component.InvokeAsync("AdminDashboard")

            </div>

        </div>
    </div>

</div>


<hr />
<table class="table table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>اسم</th>
            <th>توضیحات</th>
            <th>آیکن</th>
            <th>لینک</th>
            <th>دسته بندی</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Title</td>
                <td>@item.Description</td>
                <td>@item.Icon</td>
                <td>@item.Link</td>
            </tr>
        }
    </tbody>
</table>

MasterCard.Web/Views/Home/Index.cshtml
@using MasterCard.Web.ViewModel

@model IEnumerable<CardViewModel>

@{
    ViewData["Title"] = "Home Page";
}

 @foreach (var item in Model)
{
    <div class="col-sm-6 col-lg-4">
        <div class="panel">
            <div class="panel-body">
                <div class="media-main">
                    <a class="pull-left" href="@item.Link">
                        <img class="thumb-lg img-circle" src="@item.Icon" alt="">
                    </a>
                    <div class="info">
                        <h4>@item.Title</h4>
                        <p class="text-muted">@item.Description</p>
                    </div>
                </div>
                <div class="clearfix"></div>
                <hr />
                <a href="@item.Link" class="text-warning">@item.Link</a>
            </div>
        </div>
    </div>
    @* https://localhost:7143/images/SiteIcons/electronic.png *@
}

MasterCard.Web/Views/Shared/Components/AdminDashboard/Default.cshtml
@model MasterCard.Web.ViewModel.CardViewModel;


<form  method="post">
    <div class="modal-body">
        <div class="mt-3">
            <label class="form-label">نام</label>
            <input type="text" class="form-control" asp-for="Title" />
        </div>

        <div class="mt-3">
            <label class="form-label">توضیحات</label>
            <input type="text" class="form-control" asp-for="Description" />
        </div>


        <div class="mt-3">
            <label class="form-label">لینک</label>
            <input type="text" class="form-control" asp-for="Link" />
        </div>


        <div class="mt-3">
            <label class="form-label">آیکن</label>
            <input type="text" class="form-control" asp-for="Icon" />
        </div>

        <div class="mt-3">
            <label class="form-label">دسته بندی</label>
            <input type="text" class="form-control" />
        </div>

        <div class="mt-3">
            <label class="form-check-label" for="IsDeleted">حذف شده</label>
            <input type="checkbox" class="form-check-input" id="IsDeleted" asp-for="IsDeleted" />
        </div>

    </div>
    <div class="modal-footer">
        <button type="submit" class="btn btn-success">ایجاد</button>
        <button type="button" class="btn btn-danger" data-dismiss="modal">بستن</button>
    </div>
</form>

MasterCard.Web/Views/Shared/Components/Categories/_CategoryList.cshtml
@using MasterCard.Web.ViewModel

@model IEnumerable<CategoryViewModel>





<div id="sidebar-menu">
    <ul>
    
       @*  <li>
            <a href="index.html" class="waves-effect"><i class="md md-home"></i><span> داشبورد </span></a>
        </li> *@

        <li class="has_sub">
            <a href="#" class="waves-effect"><i class="md md-mail"></i><span> سامانه های عمومی </span><span class="pull-right"><i class="md md-add"></i></span></a>
            <ul class="has_sub">
                @foreach (var item in Model)
                {
                    <li><a href="#">@item.Title</a></li>
                }
            </ul>
        </li>

    </ul>
    <div class="clearfix"></div>
</div>

MasterCard.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <link rel="shortcut icon" href="images/favicon_1.ico">

    <title>Moltran - Responsive Admin Dashboard Template</title>

    <!-- Base Css Files -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />

    <!-- Font Icons -->
    <link href="~/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/ionicon/css/ionicons.min.css" rel="stylesheet" />
    <link href="~/css/material-design-iconic-font.min.css" rel="stylesheet">

    <!-- animate css -->
    <link href="~/css/animate.css" rel="stylesheet" />

    <!-- Waves-effect -->
    <link href="~/css/waves-effect.css" rel="stylesheet">

    <!-- Custom Files -->
    <link href="~/css/helper.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="~/js/modernizr.min.js"></script>

</head>



<body class="fixed-left">

    <!-- Begin page -->
    <div id="wrapper">

        <!-- Top Bar Start -->
        <div class="topbar">
            <!-- LOGO -->
            <div class="topbar-left">
                <div class="text-center">
                    <a href="#" class="logo"><img src="~/images/logo.png" /></a>
                </div>
            </div>
            <!-- Button mobile view to collapse sidebar menu -->
            <div class="navbar navbar-default" role="navigation">
                <div class="container">
                    <div class="">
                        <div class="pull-left">
                            <button class="button-menu-mobile open-left">
                                <i class="fa fa-bars"></i>
                            </button>
                            <span class="clearfix"></span>
                        </div>
                        <form class="navbar-form pull-left w-100 d-block" role="search">
                            <div class="form-group">
                                <input type="text" class="form-control search-bar" placeholder="جست وجو...">
                            </div>
                            <button type="submit" class="btn btn-search"><i class="fa fa-search"></i></button>
                        </form>
                    </div>
                    <!--/.nav-collapse -->
                </div>
            </div>
        </div>
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
             
            @* @await Html.Partial("CategoryList") *@
        <div class="left side-menu">
            <div class="sidebar-inner slimscrollleft">
                <!--- Divider -->
                @* <partial name="CategoryList"  />  *@
                @await Component.InvokeAsync("Categories")
                <div class="clearfix"></div>
            </div>
        </div>
 
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container">

                    @RenderBody()

                </div>

                <!-- Pls Remove -->


            </div> <!-- container -->

        </div> <!-- content -->



    </div>
    <!-- ============================================================== -->
    <!-- End Right content here -->
    <!-- ============================================================== -->
    <!-- Right Sidebar -->
    <div class="side-bar right-bar nicescroll">
        <h4 class="text-center">Chat</h4>
        <div class="contact-list nicescroll">
            <ul class="list-group contacts-list">
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-1.jpg" alt="">
                        </div>
                        <span class="name">Chadengle</span>
                        <i class="fa fa-circle online"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-2.jpg" alt="">
                        </div>
                        <span class="name">Tomaslau</span>
                        <i class="fa fa-circle online"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-3.jpg" alt="">
                        </div>
                        <span class="name">Stillnotdavid</span>
                        <i class="fa fa-circle online"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-4.jpg" alt="">
                        </div>
                        <span class="name">Kurafire</span>
                        <i class="fa fa-circle online"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-5.jpg" alt="">
                        </div>
                        <span class="name">Shahedk</span>
                        <i class="fa fa-circle away"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-6.jpg" alt="">
                        </div>
                        <span class="name">Adhamdannaway</span>
                        <i class="fa fa-circle away"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-7.jpg" alt="">
                        </div>
                        <span class="name">Ok</span>
                        <i class="fa fa-circle away"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-8.jpg" alt="">
                        </div>
                        <span class="name">Arashasghari</span>
                        <i class="fa fa-circle offline"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-9.jpg" alt="">
                        </div>
                        <span class="name">Joshaustin</span>
                        <i class="fa fa-circle offline"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
                <li class="list-group-item">
                    <a href="#">
                        <div class="avatar">
                            <img src="images/users/avatar-10.jpg" alt="">
                        </div>
                        <span class="name">Sortino</span>
                        <i class="fa fa-circle offline"></i>
                    </a>
                    <span class="clearfix"></span>
                </li>
            </ul>
        </div>
    </div>
    <!-- /Right-bar -->
    </div>
    <!-- END wrapper -->

    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/waves.js"></script>
    <script src="~/js/wow.min.js"></script>
    <script src="~/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script src="~/js/jquery.scrollTo.min.js"></script>
    <script src="~/assets/jquery-detectmobile/detect.js"></script>
    <script src="~/assets/fastclick/fastclick.js"></script>
    <script src="~/assets/jquery-slimscroll/jquery.slimscroll.js"></script>
    <script src="~/assets/jquery-blockui/jquery.blockUI.js"></script>


    <!-- CUSTOM JS -->
    <script src="~/js/jquery.app.js"></script>

</body>
</html>